blank_issues_enabled: true
contact_links:
  - name: Feature request or Idea
    url: https://github.com/codewriter-packages/UniMob/discussions/categories/ideas
    about: Suggest an idea for this project.
  - name: Question
    url: https://github.com/codewriter-packages/UniMob/discussions/categories/q-a
    about: Please ask and answer questions here.
